-- Audited concordance of the six themes; only theme_id is changed.
BEGIN;

CREATE TEMP TABLE reviewed_theme_assignments (
    id integer PRIMARY KEY,
    previous_theme integer NOT NULL,
    target_theme integer NOT NULL CHECK (target_theme BETWEEN 0 AND 5),
    expected_question text NOT NULL
) ON COMMIT DROP;

INSERT INTO reviewed_theme_assignments VALUES
    (21, 0, 4, 'Quelle affirmation sur le nouveau tricorne, porté par les personnels féminins de l''armée de Terre, est fausse ?'),
    (22, 0, 3, 'En 2024 la 7e bigrade blindée (7e BB) a expérimenté lors de l''exercice Dacian Fall 2024 un poste de commandement ?'),
    (25, 0, 2, 'Quel exercice annuel représente 2026 pour la loi de programmation militaire (LPM) en cours ?'),
    (27, 0, 1, 'Le programme Mortier Embarqué Pour l''Appui au Contact (MEPAC) est dérivé du ...'),
    (31, 0, 1, 'Laquelle de ces affirmations concernant le Missile de Moyenne Portée (MMP ou Akeron MP) est fausse ?'),
    (32, 0, 3, 'L''opération Chammal concerne ...'),
    (34, 0, 2, 'S''agissant du volume de la réserve opérationnelle de 1er niveau (RO1), quel est l''objectif visé par l''armée de Terre à l''horizon 2030 ?'),
    (38, 0, 4, 'Chaque année, le 17 janvier, la Légion étrangère fête ...'),
    (42, 0, 4, 'Une de ces affirmations concernant la Légion d''honneur est fausse. Laquelle ?'),
    (46, 0, 4, 'Quelles sont les deux couleurs de tradition des Troupes de marine ?'),
    (47, 0, 2, 'Le montant (hors pensions) alloué au ministère des Armées pour la mission Défense dans le cadre du budget 2026 s''élève à environ ...'),
    (51, 0, 3, 'L''opération de protection du Centre spatial guyanais a pour appellation ...'),
    (53, 0, 1, 'Laquelle de ces armes est en calibre 7,62 mm ?'),
    (54, 0, 4, 'Le 23 septembre, les chasseurs (subdivision de l''infanterie) commémorent ...'),
    (55, 0, 2, 'S''agissant des chars Leclerc rénovés, quelle est la cible prévue à l''horizon 2030 par la Loi de programmation militaire en cours ?'),
    (56, 0, 4, 'Le TTA 207 ...'),
    (58, 0, 1, 'Désignez l''intrus.'),
    (59, 0, 4, 'L''Aviation légère de l''armée de Terre (ALAT) a pour Saint(e)-Patron(ne) ...'),
    (61, 0, 4, 'L''auteur de la fameuse « Prière du parachutiste » est ...'),
    (63, 0, 1, 'Laquelle des affirmations suivantes concernant le pistolet semi-automatique (PSA) Glock 17 FR est fausse ?'),
    (64, 0, 4, 'Quelle est la devise du Génie ?'),
    (65, 0, 3, 'Laquelle de ces missions/opérations concerne le territoire national ?'),
    (68, 0, 1, 'Une de ces affirmations concernant le char Leclerc est fausse. Laquelle ?'),
    (72, 0, 1, 'Quel est l''intrus ?'),
    (74, 0, 4, 'La mascotte du 1er Régiment de spahis (1er RS) est ...'),
    (76, 1, 2, 'Quel pourcentage des cibles Scorpion doit être livré d''ici 2025 ?'),
    (83, 1, 2, 'Quel objectif d''EBRC Jaguar est prévu pour 2030 ?'),
    (89, 1, 0, 'En 2024, combien y a-t-il de regiment de l''aviation legere de l''armee de terre  au sein de la 4BAC ?'),
    (90, 1, 3, 'En Afrique dans le cadre du partenariat, de combien de détachement de liaison interarmes (DLIA) la France dispose t''elle en 2025 ?'),
    (91, 1, 0, 'En 2024, combien y a-t-il de brigade interarmes au sein du CFOT?'),
    (92, 1, 0, 'Combien de brigades interarmes (hors BFA) composent la force SCORPION (1ère et 3e Divisions) ?'),
    (93, 1, 2, 'Sur toute la duree de la LPM, de combien de systeme PARADE disposeront les armees ?'),
    (94, 1, 0, 'Depuis janvier 2025, quel pourcentage de la reserve operationnelle des armees represente la reserve operationnelle de l''armee de Terre ?'),
    (95, 1, 2, 'Quel a ete en 2023 l''investissement financier global dans l''infrastructure de l''armee de Terre ?'),
    (96, 1, 4, 'L''infanterie est la " Reine des batailles ". Elle est l''arme des …… derniers metres ?'),
    (97, 1, 4, 'En quelle annee a ete creee l''arme des Transmissions ?'),
    (98, 1, 4, 'En quelle annee fut creee l''arme du TRAIN (initialement nommee Train des equipages militaires) ?'),
    (99, 1, 4, 'En quelle année l''arme du Train a-t-elle acquis son autonomie ?'),
    (100, 1, 4, 'En quelle annee les unites du service du materiel ont-elles ete regroupees au sein d''une arme ?'),
    (101, 1, 4, 'En quelle année les unités du service du matériel ont-elles été regroupées au sein d''une arme ?'),
    (102, 1, 3, 'Depuis quelle annee l''armee française est-elle presente au Liban ?'),
    (103, 1, 4, 'Dans l''introduction du Livre Vert, il est question d''un ouvrage publie par l''armee de Terre : "L''exercice du metier des armes dans l''armee de Terre - Fondements et principes". En quelle annee a-t-il ete publie ?'),
    (104, 1, 0, 'Tiré du RNS 2025, qu''elle est l''année cible ou la France doit être réarmé, matériellement et moralement, pour prévenir, faire face et gagner avec ses alliés et partenaire tout conflit haute intensité dans le voisinage de l''Europe ?'),
    (105, 1, 0, 'De combien d''hommes cette division scorpion devra elle être armee ?'),
    (116, 1, 0, 'Quel est le rôle du commandement de l''armee de Terre ?'),
    (117, 1, 0, 'Quelles sont les prerogatives du major general de l''armee de Terre ?'),
    (118, 1, 0, 'Quel est le rôle de l''etat-major de l''armee de Terre ?'),
    (125, 1, 0, 'Quelle est la mission de la direction des ressources humaines de l''armee de Terre ?'),
    (129, 1, 0, 'Pourquoi la maîtrise de l''hybridite est-elle importante pour l''armee de Terre ?'),
    (132, 1, 0, 'Quel est l''objectif de faire de l''armee de Terre une composante terrestre en operation permanente ?'),
    (133, 1, 0, 'Quel est l''objectif de devenir l''armee du Cyber ?'),
    (134, 1, 0, 'Quel est l''objectif du phasage de la transformation de l''armee de Terre ?'),
    (135, 1, 0, 'Quel est l''objectif de l''Armee de Terre de combat 2024 ?'),
    (136, 1, 0, 'Quel est l''objectif principal de l''armee de Terre dans la nouvelle ere strategique ?'),
    (142, 1, 0, 'Quel document a evolue en 2005 pour s''adapter au statut general des militaires, prendre en compte la professionnalisation des armees et le nouveau cadre d''exercice du metier des armes ?'),
    (143, 1, 4, 'Quel est le rôle des traditions militaires dans l''armee de Terre ?'),
    (144, 1, 4, 'Quelle est la fonction des mascottes dans l''armee de Terre ?'),
    (145, 1, 4, 'Quelle est la fonction des tenues dans l''armee de Terre ?'),
    (146, 1, 0, 'Comment l''armee de Terre doit-elle rester prête à engager les forces terrestres ?'),
    (147, 1, 4, 'Quel est le rôle des peintres de l''armee de Terre ?'),
    (148, 1, 4, 'Quelle est la fonction des insignes dans l''armee de Terre ?'),
    (149, 1, 0, 'Quelle est la fonction des regiments dans l''armee de Terre ?'),
    (150, 1, 0, 'Qui est le General d''armee mentionne dans le livre kaki ?'),
    (151, 1, 0, 'Quel est le principe fondamental de l''exercice du commandement dans l''armee de Terre ?'),
    (152, 1, 0, 'Quels sont les deux fondamentaux de l''armee de Terre mentionnes dans armee de Terre de combat ?'),
    (153, 1, 0, 'Quelle est la source principale de credibilite de l''armee de Terre vis-à-vis de ses allies et competiteurs'),
    (154, 1, 0, 'Quelles qualites doivent preserver les unites de l''armee de Terre ?'),
    (155, 1, 0, 'Quel est le socle commun indispensable à la cohesion de l''armee de Terre ?'),
    (156, 1, 0, 'Qu''est-ce qui fait la richesse de l''armee de Terre selon l''armee de Terre de combat ?'),
    (157, 1, 0, 'Qui diffuse et entretient l''esprit guerrier dans l''armee de Terre ?'),
    (158, 1, 0, 'Quelle est la mission principale de l''armee de Terre selon le livre kaki ?'),
    (159, 1, 4, 'Les matochards  fêtent'),
    (160, 1, 4, 'La cavalerie est l''arme'),
    (161, 1, 4, 'L''artillerie est l''arme'),
    (162, 1, 4, 'Le genie est l''arme'),
    (163, 1, 4, 'Le Train est l''arme'),
    (164, 1, 4, 'Le materiel est l''arme'),
    (165, 1, 4, 'L''ALAT est l''arme'),
    (166, 1, 0, 'Quel rôle l''armee de Terre doit-elle assumer en matiere de capacites cyber ?'),
    (168, 1, 0, 'Dans le cadre de la transformation de l''armee de Terre, la 3e division a pris debut 2024 et jusqu''en 2027 l''appellation de division :'),
    (169, 1, 0, 'Les brigades interarmes (BIA) sont sectorisés et agissent dans un secteur géographique qui leur est propre tous les ?'),
    (170, 1, 0, 'Lequel de ces régiments de l''arme blindée cavalerie est rattaché à la 6e Brigade légère blindée ?'),
    (173, 1, 4, 'En 2022, l''arme des Transmissions a fêté ses :'),
    (174, 1, 0, 'En 2024, la Brigade interarmes (BIA) devient le pivot opérationnel de l''armée de Terre (cf. GRAT 2023). A combien d''hommes s''élèvent ses effectifs ?'),
    (175, 1, 4, 'Quel est le rôle des emblemes dans l''armee de Terre ?'),
    (178, 1, 4, 'Quelles sont les deux couleurs distinctives du Matériel ?'),
    (179, 1, 0, 'Laquelle de ces unités ou types d''unité effectue la maintenance "NTI3" des matériels terrestres ?'),
    (181, 1, 0, 'Le commandement de l''armee de terre est dirige par :'),
    (182, 1, 0, 'L''Inspection de l''armee de Terre (IAT) est rattachee directement au …'),
    (184, 1, 0, 'L''emploi de l''arme nucléaire est de répondre à …..?'),
    (186, 1, 3, 'De combien de groupements tactiques interarmes (GTIA) se composait la TASK FORCE La Fayette ?'),
    (187, 1, 0, 'Le modele "armee de Terre de combat" institue quatre grands commandements. Lequel n''en fait pas partie ?'),
    (188, 1, 0, 'Dans le livret " vers une armee de Terre de combat, les 4 axes sont  "être et durer", "proteger", "agir" et ?'),
    (189, 1, 0, 'Dans le cadre du modele "armee de Terre de combat", lequel de ces organismes de formation n''est pas rattache au nouveau Pôle formation de la DRHAT ?'),
    (190, 1, 0, 'Dans le cadre de la nouvelle politique de rémunération des militaires (NPRM), l''indemnité pour charge militaire (ICM) non fiscalisée et la majoration d''indemnité pour charge militaire (MICM) sont devenues :'),
    (191, 1, 0, 'Dans le cadre de la nouvelle politique de remuneration des militaires (NPRM), l''indemnite pour charge militaire (ICM) non fiscalisee et la majoration d''indemnite pour charge militaire (MICM) sont devenues :'),
    (193, 1, 0, 'Le modele "armee de Terre de combat" a 4 grands commandements. Lequel n''en fait pas partie'),
    (196, 1, 0, 'De quel comportement "être attentif aux difficultés de ses frères d''armes" relève-t-il ?'),
    (199, 1, 4, 'Quelle Arme de l''armée de terre a fêté ses 400 ans en 2022 ?'),
    (206, 1, 0, 'Dans un contexte strategique synonyme d''instabilite et d''incertitude, l''armee de Terre s''oriente vers deux fondamentaux :'),
    (207, 1, 0, 'L''emploi de l''arme atomique est de la responsabilité de ?'),
    (208, 1, 0, 'L''armee de Terre agit de maniere permanente et simultanee dans trois espaces strategiques. Une des propositions est fausse :'),
    (210, 1, 0, 'Le nouveau systeme d''alerte de l''armee de terre repose sur 3 piliers,quel est l''intrus'),
    (212, 1, 4, 'Les transmissions est l''arme'),
    (214, 1, 3, 'Laquelle de ces missions ne fait pas partie des missions interieures de l''armee de Terre ?'),
    (216, 1, 2, 'Au terme de la LPM, l’armee de l’air et de l’espace sera equipee de combien d’avions ARCHANGE ?'),
    (220, 1, 0, 'Quels sentiments fondent la « fraternité d''armes » ?'),
    (221, 1, 0, 'Quelles sont les quatre conditions nécessaires pour créer la fraternité d''armes au sein d''une unité ?'),
    (222, 1, 0, 'Qu''est-ce qui fonde la « fraternité d''armes » entre chefs et subordonnés ?'),
    (223, 1, 4, 'Quelle arme est surnommée la « Reine des batailles » et l''arme des « 300 derniers mètres » ?'),
    (225, 1, 0, 'Quelle entité a été créée en août 2023 pour intégrer les nouvelles technologies au combat ?'),
    (226, 1, 0, 'Quel est le concept clé définissant une brigade capable de s''engager sous 10 jours comme système d''armes complet ?'),
    (228, 1, 0, 'Quel est le but de la sectorisation géographique pour les brigades interarmes dans le nouveau modèle ?'),
    (230, 2, 0, 'Quel est le taux de renouvellement du premier contrat dans la MDR RH ?'),
    (239, 2, 0, 'Quel est le nombre d''effectifs du ministère des Armées en 2025 ?'),
    (241, 2, 0, 'Quel est le pourcentage des terrains militaires classés dans le réseau européen de protection de la biodiversité ?'),
    (249, 2, 0, 'Quel est l''objectif du deploiement d''un systeme divisionnaire complet et reactif ?'),
    (258, 2, 0, 'Dans le RNS 2025, la France doit se préparer à l''avenir pour rester pleinement maître de son destin national et européen à l''horizon ……?'),
    (259, 2, 3, 'En mars 2025 l''exercie Diodore 25 a expérimenté le concept de la Task Force Deep (Emploi de l''artillerie + hélico), unité de circonstance pouvant agir dans la zone ennemie d''une distance comprise entre ?'),
    (263, 2, 0, 'Les pays de l''union européenne au 01 janvier 2025 compte combien de pays membres ?'),
    (264, 2, 0, 'Le corps Européen est composé de ….'),
    (271, 2, 4, 'La loi du 28 fevrier 2012 fixe l''hommage à tous les morts pour la France le :'),
    (275, 2, 0, 'Lequel de ces pays n''est pas une nation-cadre de l''Eurocorps ?'),
    (276, 2, 0, 'Selon le Concept d''emploi des forces terrestres (CEFT) 2020-2035, l''évolution de la conflictualité s''articule autour d''un nouveau triptyque avec la compétition, l''affrontement et entre les deux …'),
    (277, 2, 0, 'Le 05 mars 2025, le Président de la République française ouvre le débat sur un dialogue stratégique sur la protection des alliés Européens par la dissuasion française . Ce dialogue s''appuie sur combien de fondamentaux ?'),
    (279, 2, 0, 'Le statut général des militaires exige, dans son article 1er (loi n°2005-270 du 24/03/2005) :'),
    (280, 2, 3, 'En février 2024 afin de contribuer à la sécurisation des flux commerciaux d''intérêt, plus particulièrement en mer rouge, quel est le nom de l''opération lancé par l''Europe ?'),
    (282, 2, 3, 'En europe, où se déroule la mission Lynx ?'),
    (283, 2, 0, 'L''emploi du 13e RDP relève du …..'),
    (287, 2, 0, 'La revue nationale stratégique 2022 fait référence à un sommet qui a réuni les chefs d''État et de gouvernement de l''Union européenne les 10 et 11 mars 2022, suite au déclenchement de la guerre en Ukraine. Où a-t-il eu lieu ?'),
    (289, 2, 0, 'Quel principe stipule qu''une erreur peut être acceptée si elle est exploitée à des fins éducatives ?'),
    (290, 2, 0, 'Qui est responsable de l''emploi opérationnel des forces et conseiller militaire du Gouvernement ?'),
    (294, 3, 0, 'Quel pourcentage des effectifs se trouve hors grands pôles urbains ?'),
    (295, 3, 0, 'Quelle part des FST représente les forces spéciales ?'),
    (297, 3, 0, 'Combien de bases opérationnelles avancées existent ?'),
    (298, 3, 0, 'Combien de maisons Athos existent en 2025 ?'),
    (299, 3, 0, 'Combien de forces de souveraineté sont mobilisées ?'),
    (301, 3, 0, 'Combien de régiments compose la B-LOG ?'),
    (302, 3, 1, 'Combien de SNLE sont en service ?'),
    (304, 3, 0, 'Quel est l''objectif stratégique de 2030 ?'),
    (306, 3, 0, 'De combien de bases opérationnelles avancées la France dispose-t-elle pour répondre à l''impératif d''être en permanence au plus près des zones de crises potentielles ?'),
    (315, 3, 0, 'Quel est l''effectif en militaires projetables prévu par le contrat opérationnel de l''armée de Terre ?'),
    (316, 3, 0, 'Quel est l''effectif de la Force opérationnelle terrestre'),
    (317, 3, 0, 'Quelle affirmation relative au Commandement des Opérations Spéciales (COS) est exacte ?'),
    (319, 3, 0, 'De combien de missions principales la B.LOG répartit ses efforts ?'),
    (320, 3, 2, 'La réserve opérationnelle est amenée à montée en puissance en 2035 avec le cap de….?'),
    (321, 3, 0, 'De combien d''unités opérationnelles disposent en 2025 la communauté cyber des armées (CCA) ?'),
    (323, 3, 0, 'En 2025 la réserve opérationnelle combattante ou spécialiste est composé de ?'),
    (325, 3, 0, 'Selon les chiffres annoncés par le CEMAT lors du  GRAT 2023, l''effectif de la force opérationnelle terrestre (FOT) restera stable. A combien d''hommes cet effectif s''élève-t-il ?'),
    (327, 3, 0, 'Quelle est la principale mission de l''armée de Terre selon le livre marron'),
    (330, 3, 0, 'Dans l''organigramme "Armée de Terre de combat 2024", sous quelle autorité le 54e Régiment de transmissions est-il placé ?'),
    (332, 3, 0, 'La commission des recours militaires (CRM) est compétente pour connaître :'),
    (333, 3, 0, 'Une mission du CCF n''est pas bonne laquelle'),
    (334, 3, 0, 'Les quatre missions principales confiées au CCF sont ?'),
    (338, 3, 0, 'Article 3 : "Toujours disponible et discipliné, je suis exemplaire dans mon comportement comme dans ma tenue". La disponibilité, c''est être toujours volontaire, se tenir prêt en permanence à l''engagement opérationnel et …'),
    (347, 3, 0, 'Quel est l''un des facteurs de supériorité opérationnelle mentionnés dans le livre marron'),
    (348, 3, 0, 'Quels sont les missions du CCF'),
    (349, 3, 0, 'La fonction stratégique "connaissance compréhension anticipation" recouvre cinq domaines : la connaissance des théâtres d''opérations, la diplomatie, la prospective et l''anticipation, la maîtrise de l''information et :'),
    (353, 3, 0, 'Qu''elles sont les trois missions de la gouvernance cybersécuritaire de la France ?'),
    (356, 3, 0, 'Toujours disponible et discipliné je suis exemplaire dans mon comportement comme dans ma tenue. La disponibilité, c''est être toujours volontaire, se tenir prêt en permanence à l''engagement opérationnel et'),
    (359, 3, 4, 'Dans quel parc parisien un monument en hommage aux soldats morts en opérations extérieures depuis 1963 a-t-il été inauguré le 11 novembre 2019 ?'),
    (367, 3, 0, 'Que prévoit le contrat opérationnel sur un cycle de base'),
    (368, 3, 0, 'La commission Armées-Jeunesse (CAJ) est :'),
    (370, 3, 0, 'Selon le général Pierre Schill, quel est le style de commandement le plus efficace au quotidien comme en opérations ?'),
    (371, 3, 0, 'Quelle est la définition de la méthode de commandement opérationnel privilégiée par l''Armée de Terre ?'),
    (372, 3, 0, 'Comment est qualifiée la mission dans l''article 9 du Code d''honneur ?'),
    (373, 3, 0, 'Quelle règle permet l''intervention des armées sur le territoire national en cas de crise majeure (missions de sécurité intérieure) ?'),
    (374, 3, 0, 'Quelle est la mission principale du Haut Comité d''évaluation de la condition militaire (HCECM) ?'),
    (376, 4, 1, 'Combien de menus peuvent être consommés froids ?'),
    (377, 4, 1, 'Combien de menus sont sans porc ?'),
    (378, 4, 1, 'Combien de menus différents sont proposés ?'),
    (387, 4, 0, 'En 2023, parmi les membres du Conseil de la fonction militaire Terre (CFMT), quel est le pourcentage de présidents ou vice-présidents de catégorie ?'),
    (388, 4, 1, 'Quel pourcentage de lipides contient cette ration ?'),
    (389, 4, 1, 'En 2024, Quel est en pourcentage le volume de livraisons réalisés dans le cadre du programme scorpion (remplacement VHC blindés…)'),
    (390, 4, 0, 'Quel part en pourcentage représente l''armée de terre dans les effectifs du Ministère des armées ?'),
    (391, 4, 0, 'En matière de fidélisation, quel est le taux visé (par le modèle MDR RH) pour le renouvellement du premier contrat de 5 ans ?'),
    (392, 4, 0, 'Quel est le pourcentage des effectifs de l''armée de Terre basés en dehors des grands pôles urbains, chiffre donné par le CEMAT lors de l''entretien accordé à l''occasion du GRAT2023 ?'),
    (393, 4, 0, 'Quelle part les forces spéciales Terre (FST) représentent-elles au sein des forces spéciales ?'),
    (394, 4, 0, 'En 2024, combien y a-t-il de division  ?'),
    (395, 4, 0, 'La dissuasion nucleaire française repose sur combien de composantes strategiques ?'),
    (396, 4, 1, 'Combien de menus peuvent être consommes froids ?'),
    (397, 4, 0, 'Quel est la duree d''un mandat d''un membre du CFMT'),
    (398, 4, 0, 'Combien y a-t-il d''ELGA au total en 2025 ?'),
    (399, 4, 0, 'Combien y a-t-il d''ELGA au total en 2024 ?'),
    (400, 4, 0, 'En 2025 combien y aura-t-il de "maisons Athos"  ?'),
    (401, 4, 0, 'A combien de principes le droit des conflits armés répond-il ?'),
    (402, 4, 0, 'Combien y a-t-il de groupements à la Brigade des Sapeurs-Pompiers de Paris ?'),
    (403, 4, 0, 'De combien de forces de souveraineté la France dispose t-elle ?'),
    (404, 4, 0, 'Combien de regiments la brigade logistique (B-LOG) a-t-elle sous son commandement ?'),
    (405, 4, 0, 'nombre de zone de defense et de securite:'),
    (406, 4, 0, 'nombre de zone terre:'),
    (407, 4, 1, 'De combien de SNLE (Sous-marins Nucléaires Lanceurs d''Engins) la France dispose-t-elle en 2023 ?'),
    (408, 4, 0, 'Combien d''objectifs stratégiques la France se fixe-t-elle pour 2030 ?'),
    (409, 4, 0, 'Combien de commandement de zone terre (COMZT) y-a-t-il en France ?'),
    (410, 4, 0, 'De combien de principes les qualités du chef "Au contact" relèvent-elles ?'),
    (411, 4, 0, 'Combien de divisions le 2e niveau des forces projetables de l''armée de Terre comprend-il ?'),
    (412, 4, 3, 'Combien de compagnies sont déployées dans les Forces armées en Guyane'),
    (413, 4, 1, 'Quelle est la portée du Mortier de 120 mm rayé, tracté (Mo 120) en Km'),
    (414, 4, 0, 'Combien y a-t-il de Services d''information et de relations publiques des Armées (SIRPA) Terre images (STI) ?'),
    (415, 4, 0, 'De combien de forces de présence la France dispose t-elle ?'),
    (416, 4, 0, 'La brigade des militaires de la sécurité civile BMSC est composé de combien de régiment  ?'),
    (417, 4, 0, 'Combien y-a-t-il de brigades Spécialisées dans l''armée de terre au combat ?'),
    (418, 4, 0, 'En 2023, de combien de centres disposait en métropole le Service militaire volontaire (SMV) ?'),
    (419, 4, 0, 'Combien de semaines la formation générale initiale des EVI dure-t-elle ?'),
    (420, 4, 1, 'Combien de menus differents sont proposes ?'),
    (421, 4, 0, 'En 2023, de combien de centres disposait en metropole le Service militaire volontaire (SMV) ?'),
    (422, 4, 0, 'En combien de zones Terre est découpé le territoire national métropolitain ?'),
    (423, 4, 0, 'La France actualise son ambition strategique pour 2030. Cette vision s''incarne à travers combien d''objectifs strategiques ?'),
    (424, 4, 0, 'En 2024, combien y a-t-il de regiment d''infanterie  ?'),
    (425, 4, 0, 'Combien de qualités de chef sont déclinées dans le Livre Bleu ?'),
    (426, 4, 0, 'Au 1er janvier 2024, combien de brigades au total l''armée de Terre comprend-elle ?'),
    (427, 4, 0, 'Combien y a-til de bases de défense déployées au 1er janvier 2023 en outre mer et à l''étranger ?'),
    (428, 4, 1, 'Quelle est la capacité maximale d''emport du CAESAR (en coups complets) ?'),
    (429, 4, 1, 'Quelle est la portée maximale du CAESAR en KM'),
    (430, 4, 1, 'Dans la gamme Scorpion combien de Jaguar ont été livrés à l''armée de Terre en 2024 ?'),
    (431, 4, 0, 'Dans les annees à venir, la division scorpion doit être capable de se deployer en combien de jours ?'),
    (432, 4, 0, 'Combien d''États membres l''OTAN compte-t-elle depuis mars 2024 ?'),
    (433, 4, 1, 'Quelle est la portée maximale de la roquette M31 du Lance-Roquette Unitaire (LRU)'),
    (434, 4, 0, 'Combien y a-til de bases de défense déployées au 1er janvier 2023 ?'),
    (435, 4, 2, 'D''ici à  2028, Combien de MEPAC seront livrés à l''armée de Terre ?'),
    (436, 4, 0, 'Le CFMT compte combien de membre ?'),
    (437, 4, 0, 'En 2024, combien y a-t-il de regiment de 800 à 1000h ?'),
    (439, 4, 1, 'Dans la gamme Scorpion combien de Griffon ont été livrés à l''armée de Terre en 2024 ?'),
    (440, 4, 1, 'Dans la gamme Scorpion combien de Serval ont été livrés à l''armée de Terre en 2024 ?'),
    (442, 4, 3, 'En 2024, quel est l''effectif militaire des forces françaises aux émirats arabes unis (FFEAU) ?'),
    (443, 4, 0, 'En 2024, combien y avait-il de forces prepositionnees ?'),
    (444, 4, 0, 'En 2024, combien y avait-il de forces de souverainete ?'),
    (445, 4, 2, 'Selon les chiffres annoncés par le CEMAT lors du GRAT 2023, combien de véhicules GRIFFON l''armée de Terre devrait-elle compter en 2030 ?'),
    (464, 4, 3, 'Le mandat de la FINUL a débuté en'),
    (467, 4, 3, 'Quand l''OTAN est-elle intervenue au Kosovo ?'),
    (479, 4, 0, 'Dans l''accroissement de la reactivite, en quelle annee la division scorpion doit être operationnelle ?'),
    (481, 4, 0, 'A quel horizon une division '' bonne de guerre serait-elle constituer ?'),
    (482, 4, 1, 'Une défense française robuste - De combien est dotée en drones l''armée de Terre en 2024/2025 (chiffres MINARM 2024) ?'),
    (483, 4, 0, 'Combien de réservistes l''armée de Terre recrute-t-elle par an'),
    (484, 4, 0, 'Combien d''hommes devront composer la brigade de decision de la division scorpion ?'),
    (485, 4, 3, 'Pour la securisation de JOP, combien de soldats ont ete mobilises ?'),
    (486, 4, 0, 'Quel est le nombre d''hommes dans les éléments divisionnaires'),
    (487, 4, 0, 'Quel est le nombre d''hommes dans une brigade de décision'),
    (488, 4, 0, 'Quel est le nombre d''hommes dans une brigade médiane'),
    (489, 4, 3, 'Combien de soldats ukrainiens ont été formés en 2024 en France'),
    (490, 4, 3, 'Lors de l''operation JOP 2024, combien d''homme la FOT a-t-elle engagee ?'),
    (491, 4, 3, 'En moyenne sur 2024, combien y avait-il de soldats en posture operationnelle ?'),
    (492, 4, 3, 'À quelle date la MINUSMA a-t- elle été créée ?'),
    (493, 4, 1, 'Le lancement du satellite militaire CSO-3 a été effectué en ?'),
    (494, 4, 0, 'Quels sont les effectifs de l''armée de terre en 2025 (Militaires+civils) ?'),
    (495, 4, 2, 'La cible en effectifs militaires et civils (réservistes compris) du ministère des armées est fixée, à l''horizon 2030, à :'),
    (496, 4, 0, 'Quels sont les effectifs du Ministère des Armée en 2025 (Militaires+civils) ?'),
    (497, 4, 1, 'Quelle est la date limite d''utilisation optimale de cette ration ?'),
    (498, 4, 1, 'Quel est le poids approximatif de la Gazelle ?'),
    (499, 4, 1, 'Quel est le poids approximatif du Mistral ?'),
    (500, 4, 1, 'Quelle est la longueur de la ration en millimetres ?'),
    (501, 4, 1, 'Quel est le poids approximatif du VBCI ?'),
    (502, 4, 1, 'Combien de kcal contient cette ration ?'),
    (503, 4, 1, 'Quel est le canon principal du VBCI ?'),
    (504, 4, 1, 'Quel est le canon principal du ERC-90 Sagaie ?'),
    (505, 4, 1, 'Quel est le canon principal du Tigre ?'),
    (506, 4, 1, 'Quel est la portee maximale du Mistral ?'),
    (507, 4, 1, 'Quel est le poids approximatif du Tigre ?'),
    (508, 4, 1, 'Quel est le poids approximatif du Milan ?'),
    (509, 4, 1, 'Quel est le poids approximatif du VAB ?'),
    (510, 4, 1, 'Quel est le poids approximatif du Cougar ?'),
    (511, 4, 1, 'Quel est le canon principal du VAB ?'),
    (512, 4, 1, 'Quel est la portee maximale du Milan ?'),
    (513, 4, 1, 'Quel est le poids approximatif du ERC-90 Sagaie ?'),
    (514, 4, 1, 'Quel est le canon principal du Cougar ?'),
    (515, 4, 1, 'Quel est le canon principal de la Gazelle ?'),
    (516, 4, 0, 'Quels sont les commandements de zone Terre ?'),
    (517, 4, 0, 'Quelles sont les types de mesures de coordination externes ?'),
    (518, 4, 0, 'Quel est l''objectif de la structure integree du maintien en condition operationnelle des materiels terrestres ?'),
    (519, 4, 1, 'Quel est le moteur du VBCI ?'),
    (520, 4, 1, 'Quel est le moteur du VAB ?'),
    (521, 4, 1, 'Quel est le moteur du ERC-90 Sagaie ?'),
    (522, 4, 1, 'Quel est le moteur du Tigre ?'),
    (523, 4, 0, 'Quel est le rôle du commandement de la force et des operations terrestres ?'),
    (524, 4, 0, 'Quel est le rôle du commandement du combat futur ?'),
    (525, 4, 1, 'Quelle est la particularite de l''emballage de cette ration ?'),
    (526, 4, 0, 'Pourquoi l''entraînement doit-il être adapte à la haute intensite ?'),
    (527, 4, 0, 'Pourquoi est-il important de credibiliser le statut de Nation-cadre ?'),
    (528, 4, 0, 'Pourquoi le developpement de l''anticipation et de la prospective est-il important ?'),
    (529, 4, 0, 'Pourquoi la preservation de l''attractivite et l''amelioration de la fidelisation sont-elles importantes ?'),
    (530, 4, 0, 'Pourquoi le developpement du sentiment d''appartenance à la Communaute Terre est-il important ?'),
    (531, 4, 0, 'Pourquoi la facilitation du fonctionnement quotidien est-elle importante ?'),
    (532, 4, 0, 'Quelle est la synthese des mouvements du C2 lies à la transformation ?'),
    (533, 4, 0, 'Quel est l''objectif de l''appropriation du combat de demain ?'),
    (534, 4, 0, 'Quel est l''objectif de la coherence du systeme de formation ?'),
    (535, 4, 0, 'Quel est l''objectif de la preparation de la transition vers l''economie de guerre ?'),
    (536, 4, 0, 'Quel est l''objectif de l''ancrage sur le TN metropolitain ?'),
    (537, 4, 0, 'Quel est l''objectif de la refonte du modele de reserve ?'),
    (538, 4, 0, 'Quel est l''objectif du pilotage des domaines fonctionnels ?'),
    (540, 4, 0, 'Quelles sont les quatre etapes aujourd''hui dans l''exercice du commandement ?'),
    (541, 4, 0, 'Quel est le nombre d''etapes aujourd''hui dans l''exercice du commandement ?'),
    (542, 4, 0, 'Quelles sont les qualites fondamentales de l''esprit guerrier ?'),
    (543, 4, 0, 'Quelle transition doit être effectuee dans l''exercice du commandement ?'),
    (544, 4, 0, 'La justice dans le commandement requiert du chef certains principes ? Trouver l''intrus.'),
    (545, 4, 0, 'Quel est l''objectif principal du livre bleu ?'),
    (546, 4, 0, 'Quelle est la finalite operationnelle "Être et Durer" ?'),
    (547, 4, 0, 'Quelle est la finalite operationnelle "Proteger" ?'),
    (548, 4, 0, 'Quels sont les six principes decrits dans le livre bleu ?'),
    (549, 4, 0, 'Quelle est la premiere condition de l''humanite dans le commandement ?'),
    (556, 4, 0, 'L''esprit de decision dans le commandement requiere certaines valeurs, une n''est pas la bonne.'),
    (557, 4, 0, 'Quels sont les axes de developpement individuel et collectif sur lesquels repose l''esprit guerrier ?'),
    (558, 4, 0, 'Quel est le sens de l''equite mentionne dans le livre bleu ?'),
    (559, 4, 0, 'Dans le principe de confiance, il est dit qu''elle peut se bâtir en s''appuyant notamment sur … ?'),
    (561, 4, 0, 'Quels elements doivent être cultives dans le systeme regimentaire ?'),
    (562, 4, 0, 'Quels sont les atouts à valoriser pour cultiver les forces morales ?'),
    (563, 4, 0, 'Quel est le titre du preambule du livre Kaki " Aux sources de … " ?'),
    (565, 4, 0, 'Le commandement s''exerce en permanence dans trois dimensions distinctes mais complementaires. Une n''est pas bonne.'),
    (566, 4, 0, 'Quelle est la finalite operationnelle "Agir" ?'),
    (567, 4, 1, 'Quels renforcements capacitaires sont necessaires pour disposer d''un outil de combat coherent ?'),
    (568, 4, 0, 'Quel principe prône l''exigence dans le commandement ?'),
    (587, 4, 0, 'Lequel de ces régiments n''est pas subordonné à la 11e BP ?'),
    (588, 4, 0, 'Que signifie le sigle CIAT ?'),
    (589, 4, 0, 'La zone de responsabilité de la BSPP s''étend sur :'),
    (590, 4, 0, 'Qu''elle est la durée de formation militaire dans un régiment du service militaire volontaire (RSMV) ?'),
    (591, 4, 1, 'Une défense française robuste - De combien est dotée en véhicules blindés l''armée de Terre en 2024/2025 (chiffres MINARM 2024) ?'),
    (593, 4, 0, 'Combien y a t-il de commandements de niveau brigade dans le modèle de l''armée de terre de combat ?'),
    (594, 4, 0, 'Combien d''objectifs stratégiques la France se fixe-t-elle (RNS 2025) pour atteindre son ambition et concourir au renforcement des fonctions stratégiques ?'),
    (595, 4, 0, 'Les 6 principes fondamentaux qui ont servi à forger notre armée professionnelle sont donc déclinés en ……..'),
    (596, 5, 4, 'En 2017, le CFIM de la 11e Brigade parachutiste, installé à Caylus, a reçu le drapeau du :'),
    (598, 4, 0, 'Quelle brigade ne fait pas partie de la 3DIV ?'),
    (599, 4, 0, 'Lequel de ces régiments est un organisme à vocation interarmées Terre (OVIA-T) ?'),
    (600, 4, 0, 'Quel unité a mis au point des techniques de réparations industrielles pour assurer une maintenance rapide, sûre et au millimètre près au profit du VBMR-L ?'),
    (601, 4, 1, 'En version cargo, l''hélicoptère COUGAR AS 532 peut héliporter :'),
    (602, 4, 0, 'La répartition par catégorie de l''armée de terre en 2025 est  ?'),
    (603, 4, 1, 'L''ensemble de parachutage du combattant (EPC) permet de parachuter :'),
    (604, 4, 0, 'La tranche d''âges pour intégrer un SMV est ?'),
    (605, 4, 0, 'Dans l''organigramme "Armée de Terre de combat 2024", sous quelle autorité le 61e Régiment d''artillerie est-il placé ?'),
    (606, 4, 0, 'Un seul régiment d''artillerie est équipé de lance-roquettes unitaires (LRU). Il s''agit du …'),
    (607, 4, 1, 'Dans quel régiment les deux premiers véhicules JAGUAR ont- ils été livrés en décembre 2021 ?'),
    (608, 4, 0, 'Quels régiments français la Brigade franco-allemande a-t-elle sous son commandement ?'),
    (609, 4, 0, 'Lequel de ces régiments ne fait pas partie de la 9e Brigade d''infanterie de marine (9e BIMa) ?'),
    (611, 4, 0, 'Laquelle de ces formations de l''armée de Terre ne fait pas partie des forces de présence (forces prépositionnées)'),
    (612, 4, 0, 'Laquelle de ces formations ne fait pas partie de la 9e Brigade d''infanterie de marine (9e BIMa) ?'),
    (613, 4, 0, 'Laquelle de ces formations n''appartient pas à la 9e Brigade d''infanterie de marine (9e BIMa)'),
    (614, 4, 0, 'Laquelle de ces formations ne fait pas partie de la Brigade franco-allemande ?'),
    (615, 4, 0, 'Laquelle de ces formations n''appartient pas à la 11 11e Brigade parachutiste ?'),
    (616, 4, 0, 'En 2025 la réserve citoyenne  est composé de ?'),
    (617, 4, 0, 'Quel est la durée de la préparation militaire Terre (PMT) ?'),
    (618, 4, 0, 'Le reseau doctrinal Terre est organise en :'),
    (619, 4, 0, 'Dès 2027 la brigade logistique (B.LOG) devra appuyer et soutenir dans l''engagement haute intensité et dans la durée une division comprenant ?'),
    (620, 4, 2, 'Quelle cible du programme SCORPION est correcte ?'),
    (621, 4, 1, 'Une défense française robuste - De combien est dotée en hélicoptères l''armée de Terre en 2024/2025 (chiffres MINARM 2024) ?'),
    (623, 4, 0, 'Dans le RNS 2025, la France doit se préparer à un engagement majeur de haute intensité à l''horizon……?'),
    (624, 4, 0, 'Laquelle de ces formations ne fait pas partie de la 9 e Brigade d''infanterie de marine (9e BIMa)'),
    (625, 4, 1, 'Quels sont les caractéristiques correctes du mortier embarqué pour l''appui au contact (MEPAC)  ?'),
    (626, 4, 0, 'Chaque année, combien de jeunes passent dans les rangs de l''Armée de Terre ?'),
    (627, 4, 0, 'Chaque année, combien de jeunes sont recrutés dans l''active (armée de Terre) ?'),
    (628, 4, 0, 'Combien de formations de l''armée de Terre au 01 juillet 2025 deviendront autonomes en matières de ressources humaines ?'),
    (629, 4, 0, 'En 2022, quel est l''âge moyen des militaires de l''armée de terre ?'),
    (630, 4, 0, 'Sous l''autorité de quelle brigade le 16e Bataillon de chasseurs à pied est-il placé ?'),
    (631, 4, 0, 'Laquelle de ces formations entre dans la composition des FASOI ?'),
    (632, 4, 0, 'Combien de brigade composent la 3e division ?'),
    (633, 4, 0, 'Combien de brigade composent la 1re division ?'),
    (634, 4, 0, 'De combien de temps forts la JDC Rénové est divisé ?'),
    (635, 4, 2, 'En 2023, cout unitaire d''un griffon ?'),
    (637, 4, 0, 'Combien de membres, de groupe et durée d''un mandat au CFMT'),
    (638, 4, 0, 'Laquelle de ces unités n''est pas une base école de l''aviation légère de l''armée de terre ?'),
    (639, 4, 0, 'La 4e Brigade d''aérocombat (4e BAC) est composé de'),
    (640, 4, 0, 'Quelle brigade ne fait pas partie du CALT ?'),
    (641, 4, 0, 'Combien de village destinés aux blessés et à leur famille a été lancée par le CNSD ?'),
    (642, 4, 0, 'Les IFN sont définis par quel article du code pénal ?'),
    (643, 4, 1, 'Le mortier de 120 mm embarqué peut tirer une salve de douze obus en moins de ?'),
    (644, 4, 1, 'Le mortier de 120 mm embarqué peut tirer une salve de douze obus en mois de ?'),
    (645, 4, 0, 'Combien d''unités du SMV sont réparties sur les 7 sites en Hexagone ?'),
    (648, 4, 0, 'Chaque année, combien de jeunes s''engagent dans la réserve (armée de Terre) ?'),
    (649, 4, 0, 'Quelle brigade ne fait pas partie de la 1DIV ?'),
    (650, 4, 2, 'En 2021, le coût unitaire du canon CAESAR était d''environ …'),
    (651, 4, 0, 'Combien de régiments composent la B.LOG ?'),
    (652, 4, 0, 'L''échelon national d''urgence renforcé (ENU-R) peut être projetée depuis le territoire national en …..'),
    (653, 4, 0, 'A quelle brigade le 126e Régiment d''infanterie est-il rattaché ?'),
    (654, 4, 0, 'Chaque année, combien de jeunes s''engagent dans les rangs du service militaire adapté ou service militaire volontaire ?'),
    (655, 4, 0, 'Le nouveau modèle de l''armée de terre de combat en 2024 a permis la création de 16 brigades en complément des 9 existantes quelles sont-elles ?'),
    (656, 4, 0, 'Parmi ces régiments, lequel est subordonné à une brigade de la 3e Division ?'),
    (657, 4, 1, 'Le 1er MEPAC a été livré en décembre 2024 au ?'),
    (658, 4, 2, 'D''ici à 2030, la France souhaite atteindre………  ?'),
    (659, 4, 0, 'quelle brigade le 126e Régiment d''infanterie est-il rattaché ?'),
    (661, 4, 0, 'Que veut dire AID'),
    (662, 4, 0, 'Dans quel axe de l''organigramme armée de terre au combat 2024 se situe le COMZT ?'),
    (663, 4, 0, 'Dans quel axe de l''organigramme armée de terre au combat 2024 se situe la 1ere DIVISION ?'),
    (664, 4, 0, 'Dans quel axe de l''organigramme armée de terre au combat 2024 se situe la STAT ?'),
    (665, 4, 1, 'Le Patroller est un drone tactique de renseignement conçu par'),
    (668, 4, 0, 'A l''été 2025, la 19e brigade d''artillerie sera renforcé par deux officiers de liaison, quels sont leur nationalité ?'),
    (669, 4, 1, 'Le nouveau fusil d''assaut HK 416F, destiné à remplacer le FAMAS, est de fabrication …'),
    (670, 4, 1, 'L''hélicoptère H160M, "Guépard", n''est pas voué à remplacer'),
    (671, 4, 1, 'Le système de déminage SOUVIM est de conception :'),
    (676, 4, 0, 'Le 519e régiment du train est spécialisé dans ?'),
    (678, 4, 1, 'Parmi ces équipements, quel est l''intrus ?'),
    (680, 4, 1, 'Le DT46 est un …….?'),
    (682, 4, 0, 'Dans une economie capable de soutenir l’effort de guerre, une de ces reponses est fausse'),
    (683, 4, 0, 'Quel projet a pour titre " Acceleration de la Transformation à Hauteur des Engagements de l''Avenir ?'),
    (684, 4, 1, 'Lequel des systemes ou materiels suivants n''est pas en service dans l''artillerie ?'),
    (685, 4, 1, 'L''armée de Terre a lancé sa modernisation avec le programme SCORPION, qui se prolongera avec un projet capacitaire pour l''horizon 2040. Quel est son nom ?'),
    (686, 4, 3, 'Suite à quel attentat le plan VIGIPIRATE est-il appliqué sans discontinuité ?'),
    (687, 4, 0, 'La CISPAT est rattachée :'),
    (688, 4, 0, 'Les Régiments d’Instruction et d’Intervention de la Sécurité Civile  (RIISC) et l''Unité d’Instruction et d’Intervention de la Sécurité Civile (UIISC) appartiennent …'),
    (692, 4, 1, 'Quelle caractéristique du GRIFFON est incorrecte ?'),
    (693, 4, 1, 'Le nouveau pistolet Glock 17-FR, destiné à remplacer les PAMAC 50 et PA MAS G1 de l''armée française, est de conception...'),
    (697, 4, 3, 'Du 23 au 26 mars 2025, les armées françaises se sont entrainées dans un scénario de guerre réaliste, dans l''Ouest de la France quel est le nom de cet exercice ?'),
    (700, 4, 0, 'Dans la revue nationale stratégique 2022, il est question à plusieurs reprises de BITD. Que signifie ce sigle ?'),
    (713, 4, 1, 'Tous sont des drones sauf un lequel ?'),
    (725, 4, 0, 'Quelle brigade ne fait pas partie du CAPR ?'),
    (729, 4, 0, 'La BANC est une nouvelle entité créée en 2024. Que signifie ce sigle ?'),
    (730, 4, 0, 'Dans l''organigramme "Armée de Terre de combat 2024", quelle brigade, dissoute en 1998, est recréée sous l''autorité du Commandement des actions dans la profondeur et du renseignement (CAPR) ?'),
    (731, 4, 0, 'Les RIISC n° 1 - 4  et 7 sont subordonnés à ?'),
    (733, 4, 1, 'Quel est le nom du drone français validé par la DGA en 2025 qui se distingue par sa capacité à opérer à 13 700 mètres et offrant une autonomie de 20 heures ?'),
    (735, 4, 1, 'Lequel n''est pas un véhicules d''artillerie'),
    (736, 4, 1, 'Comment se nomme le système radar de trajectographie permettant de localiser en temps réel les batteries adverses, en service dans l''Artillerie ?'),
    (742, 4, 1, 'Le programme FÉLIN comprend un ensemble d''études qui permettent d''améliorer les capacités du soldat dans cinq fonctions essentielles. Parmi ces quatre propositions, laquelle ne correspond pas à une fonction essentielle ?'),
    (743, 4, 0, 'Le CENTIAL-51e RI a changé de nom en 2021. Quelle est sa nouvelle appellation ?'),
    (744, 4, 0, 'La brigade logistique (B.LOG) fait partie de quel commandement ?'),
    (745, 4, 3, 'L''exercie Diodore 25 implique quel commandement Alpha et de brigade déployée ?'),
    (746, 4, 0, 'Le BRCE est une entité de ……'),
    (749, 4, 3, 'L''exercice Defnet est un exercice annuel qui est conduit par ?'),
    (751, 4, 0, 'Que signifie l''acronyme CIRFA ?'),
    (752, 4, 0, 'De qui doit-on la phrase  : " Ce sont les armées qui gagnent les batailles, mais ce sont les peuples qui gagnent les guerres " ?'),
    (753, 4, 0, 'L''OGZDS est subordonne au :'),
    (754, 4, 0, 'Le COMZT est subordonne au :'),
    (755, 5, 0, 'Quel est le nom complet du Centre d''entraînement au combat (CENTAC) situé à Mailly-le-Camp ?'),
    (756, 4, 0, 'CAEC signifie :'),
    (757, 4, 0, 'Que veux dire le sigle CIRFA ?'),
    (758, 4, 0, 'Que veut dire C.E.R.H.S ?'),
    (759, 4, 0, 'Que veut dire C.I.C.D.E ?'),
    (760, 4, 0, 'Que signifie le sigle CIAE ?'),
    (761, 4, 0, 'Que veut dire le sigle CNSD ?'),
    (762, 4, 0, 'L''action logistique combine son action dans trois segments : la logistique de l''arrière, la logistique de l''avant et la logistique'),
    (763, 4, 0, 'L''action logistique combine son action dans trois segments : la logistique de l''arrière, la logistique de l''avant et la logistique :'),
    (764, 4, 0, 'Quelle unité développe depuis octobre 2023 les techniques de leurrage ?'),
    (766, 4, 0, 'Qu''est ce qu''une brigade "bonne de guerre" ?'),
    (767, 4, 0, 'Lequel de ces organismes est devenu en 2021 un organisme à vocation interarmées Terre (OVIA-T) ?'),
    (769, 4, 0, 'Le CRR-Fr est subordonné au…….'),
    (772, 4, 0, 'Selon le livre bleu, que doit faire un chef militaire lorsqu''il rencontre des situations imprévues ?'),
    (773, 4, 1, 'Quelles sont les deux principales plateformes intégrées dans le projet SCORPION'),
    (774, 4, 1, 'La lunette thermique MIRA est destinée à l''équipement du :'),
    (779, 4, 3, 'Suite aux destructions du cyclone Chido à Mayotte quel est le nom du bataillon créer en l''a circonstance ?'),
    (782, 4, 0, 'Les sept brigades spécialisés sont réparties entre ?'),
    (783, 4, 1, 'Quel est le rôle principal de l’hélicoptère d’attaque TIGRE'),
    (784, 4, 1, 'Quel est le rôle principal de l’hélicoptère de manœuvre et d’assaut CAÏMAN'),
    (785, 4, 0, 'L''Inspection de l''armée de Terre (IAT) est rattachée directement au ...'),
    (786, 4, 0, 'Que signifie CFOT ?'),
    (787, 4, 0, 'L''annee 2024 voit la creation d''un nouveau commandement, le CCF, qui signifie :'),
    (788, 4, 0, 'Que veut dire le sigle CND ?'),
    (789, 4, 0, 'Que veut dire le sigle CCF ?'),
    (790, 4, 0, 'De quel principe les qualités de hauteur de vue, de fermeté, de sens de l''équité et de discernement relèvent-elles ?'),
    (791, 4, 0, 'Dans cet extrait du Livre Vert : "... le soldat a besoin de cultiver un fort ethos guerrier et une capacité de discernement ...", le mot grec ethos est employé. De quel mot français se rapproche-t-il ?'),
    (792, 4, 0, 'Le CATNC succède à ……'),
    (793, 4, 0, 'Le commandement de la légion étrangère (COMLE) et le commandement de l''avion légère de l''armée de terre (ALAT) sont sous l''autorité de ?'),
    (794, 4, 0, 'Quelles sont les 3 composantes interarmées et interministérielles du génie militaire ?'),
    (795, 4, 1, 'Les tenues de sport "rénovées" de l''armée de Terre sont fabriquées par l''équipementier :'),
    (799, 4, 0, 'L''objectif stratégique numéro 1 s''intitule "Une dissuasion nucléaire robuste et ..." :'),
    (800, 4, 0, 'Quels sont les cinq champs de priorisation de l''hybridité choisis par la France ?'),
    (804, 4, 0, 'La subsidiarité vise à confier au niveau hiérarchique le plus pertinent la conception et la conduite d''une action. Elle présente le triple avantage de la valorisation des échelons subordonnés, du renforcement de la confiance collective et ...'),
    (805, 4, 0, 'La subsidiarité vise à confier au niveau hiérarchique le plus pertinent la conception et la conduite d''une action. Elle présente le triple avantage de la valorisation des échelons subordonnés, du renforcement de la confiance collective et …'),
    (806, 4, 0, 'Quels sont les quatre axes fondamentaux portés par le CCF'),
    (807, 4, 0, 'Quel est l''objectif principal du document "L''alliance du sens et de la force" ?'),
    (808, 4, 0, 'Les quatre priorites de la Revue nationale strategique 2025 sont :'),
    (809, 4, 0, 'Combien de régiments le Commandement des actions spéciales terre (CAS-T) a-t-il sous son commandement ?'),
    (810, 4, 0, 'La France dispose d''une dissuasion nucléaire articulé autour de…..?'),
    (811, 4, 0, 'Les sites d''accueil de la JDC dans l''armée de Terre représente…..?'),
    (813, 4, 0, 'Quelles sont les aptitudes que doit posséder un chef selon le Livre Bleu ?'),
    (814, 4, 0, 'il y a 3 vertus cardinales de l''armée de terre,Trouver l''intrus'),
    (816, 4, 0, 'Quel est le rôle du chef dans le commandement par intention'),
    (817, 4, 0, 'Quelle est la discipline exigée pour celui qui obéit dans le commandement par intention'),
    (821, 4, 1, 'Le projet LEIA (levier Extraits à l''aide de l''IA) est un projet lancé par ?'),
    (822, 4, 0, 'Le 61e régiment d''artillerie est spécialisé dans ?'),
    (823, 4, 0, 'La CABAT dépend hiérarchiquement :'),
    (825, 4, 1, 'Lequel n''est pas un véhicules Du génie'),
    (826, 4, 0, 'L''EMPT a été créée en septembre 2022. Que signifie ce sigle ?'),
    (827, 4, 0, 'L''EMPT a ete cree en septembre 2022. Que signifie ce sigle ?'),
    (828, 4, 0, 'Lequel des organismes de formation suivants ne fait pas partie des ecoles militaires de Saumur ?'),
    (829, 4, 0, 'Les forces terrestres comportent des unités agissant dans chacun des 3 domaines de la cyberdéfense : lutte informatique offensive, défensive et ... :'),
    (830, 4, 1, 'Qu''est-ce qui distingue l''innovation planifiée de l''innovation participative'),
    (831, 4, 0, 'Laquelle de ces affirmations concernant la Brigade des sapeurs pompiers de Paris (BSPP) est fausse'),
    (833, 4, 1, 'Où est assemblee cette ration ?'),
    (834, 4, 0, 'Sous quelle autorité le service interarmées des munitions (SIMu) est-il placé ?'),
    (835, 4, 0, 'Le SMV est rattaché à ?'),
    (838, 4, 3, 'En quel mois/année les troupes françaises ont quitté le Mali ?'),
    (839, 4, 3, 'En quel mois/année les troupes françaises ont quitté le Niger ?'),
    (840, 4, 1, 'La FN Minimi est fabriqué ?'),
    (841, 4, 3, 'En quel mois/année les troupes françaises ont quitté le Burkina Faso ?'),
    (842, 4, 0, 'Dans le livre vert que veut dire "inter arma enim silent leges"'),
    (843, 4, 1, 'Caractéristique du JAGUAR'),
    (844, 4, 1, 'Au sein de l''armée de Terre, "Jaguar" est la dénomination choisie pour le futur…'),
    (845, 4, 1, 'Que veut dire SOUVIM'),
    (846, 4, 0, 'En 2022, quel était le taux de féminisation de l''armée de Terre ?'),
    (849, 4, 3, 'Quel nom porte l''exercice interarmées et interallié qui s''est déroulé de février à mars 2023 ?'),
    (852, 4, 0, 'Quels sont les quatre axes de l''armée de terre de combat ?'),
    (853, 4, 0, 'Quelle région présente une menace pour la sécurité et la stabilité, selon la revue stratégique'),
    (855, 4, 2, 'Que signifie l''acronyme FED ?'),
    (856, 4, 0, 'Laquelle de ces Forces ne fait pas partie des Forces de souverainete ?'),
    (858, 4, 0, 'Quel type de Medevac (évacuation médicale) n''existe pas ?'),
    (859, 4, 1, 'Le VHM est de conception ?'),
    (862, 4, 0, 'Quelle brigade ne fait pas partie du CAST-T ?'),
    (864, 4, 3, 'Le 15 août 2022, la réarticulation de la force Barkhane s''est achevée par la rétrocession aux forces maliennes de la base de'),
    (873, 4, 0, 'Quels sont les trois visages de la guerre mentionnés dans le livre vert ?'),
    (876, 4, 0, 'Quelle est la dénomination du nouveau dispositif de réhabilitation psychosociale mis en oeuvre par le ministère des Armées et dédié à l''accompagnement des militaires blessés psychiques ?'),
    (877, 4, 0, 'La JDC est obligatoire pour qui et qu''elle tranche d''âges ?'),
    (878, 4, 0, 'La discipline exige 3 qualités,Trouver l''intrus'),
    (879, 4, 0, 'Les principaux compétiteurs stratégiques de la France ont recours à des stratégies qui sont des combinaisons ambigües de modes d''action directs ou indirects, militaires ou non, légaux ou non. Quel adjectif qualifie ces stratégies ?'),
    (882, 4, 0, 'Quels sont les quatre grands commandements de l''organigramme de l''armée de terre de combat en 2024 ?'),
    (884, 4, 0, 'Une de ces affirmations concernant le Conseil de la fonction militaire Terre (CFMT) est fausse. Laquelle ?'),
    (885, 4, 1, 'Laquelle de ces affirmations concernant le nouveau système de drones tactiques (SDT Patroller) est fausse ?'),
    (886, 4, 0, 'Laquelle de ces affirmations concernant le Conseil superieur de la fonction militaire (CSFM) est fausse ?'),
    (888, 4, 0, 'Quelle est la vision des soldats concernant la réalité morale du combat ?'),
    (889, 4, 0, 'Quel est l''impact de l''information et de la participation sur les subordonnés ?'),
    (890, 4, 3, 'Le retour de la "Grammaire Nucléaire" résulte du conflit…...'),
    (891, 4, 0, 'Sur le visuel de la vision stratégique du CEMAT, on retrouve les quatre axes qu''il a décrits lors du GRAT 2023. Ces axes sont : "être et durer", "protéger", "agir" et :'),
    (892, 4, 0, 'Dans quel axe de l''organigramme armée de terre au combat 2024 se situe la DRHAT ?'),
    (893, 4, 0, 'Que veut dire IFN ?'),
    (894, 4, 3, 'Dans le Livre Vert, il est question des engagements de la France au Levant. Lequel de ces pays ne fait pas partie de la région du Levant ?'),
    (895, 4, 1, 'Le système d''artillerie LRM/LRU est de conception :'),
    (897, 4, 3, 'De 2024 à 2025, les armées françaises ont participé à la formation des bataillons du désert, quel est le pays qui en a fait la demande ?'),
    (898, 4, 0, 'Que veux dire le sigle JDC ?'),
    (899, 4, 0, 'Lequel des organismes de formation suivants ne fait pas partie des Écoles militaires de Saumur ?'),
    (901, 4, 0, 'Quelle brigade est l''autorité de tutelle du 68e Régiment d''artillerie d''Afrique (68e RAA) ?'),
    (903, 4, 0, 'Quelle brigade ne fait pas partie du commandement de l''appui et de la logistique de theâtre (CALT) ?'),
    (904, 4, 0, 'Quelle est la définition de l’excellence selon le livre orange'),
    (906, 4, 0, 'La PAC concerne :'),
    (907, 4, 1, 'La PEGP concerne'),
    (908, 4, 0, 'Quelles sont les fonctions stratégiques définies par le Livre blanc ?'),
    (909, 4, 0, 'Quelle est l''importance de la conscience morale pour le soldat ?'),
    (912, 4, 0, 'La participation peut revêtir deux formes qui sont…..'),
    (913, 4, 0, 'Le 54e régiment d''artillerie est spécialisé dans ?'),
    (914, 4, 0, 'Quels sont les principaux défis mentionnés concernant la sécurité des approvisionnements'),
    (915, 4, 0, 'Parmi ces qualités, laquelle relève du principe d''humanité ?'),
    (916, 4, 0, 'Lequel de ces services et directions ne dépend pas du Secrétariat général pour l’administration (SGA) ?'),
    (917, 4, 0, 'Parmi ces propositions, laquelle ne fait pas partie des principes à respecter dans la conduite de l''action armée ?'),
    (918, 4, 0, 'Parmi ces qualités, laquelle ne relève pas du principe de confiance ?'),
    (919, 4, 0, 'Quelle doit être la qualité majeure d''un chef dans le principe de décision ?'),
    (920, 4, 0, 'Quelles sont les vertus cardinales de l’armée de Terre ?'),
    (921, 4, 1, 'La PEGP concerne :'),
    (922, 4, 0, 'Quel est l''un des principaux défis logistiques identifiés dans le livre marron'),
    (923, 4, 0, 'Quelle est la valeur principale mise en avant dans le nouveau Code d’honneur du soldat français'),
    (926, 4, 3, 'Quel departem ent/territoire ultramarin est concerne par les operations « Nephila » ?'),
    (927, 4, 0, 'Quels sont les principaux défis mentionnés concernant les services de renseignement en 2030'),
    (931, 4, 0, 'Les anciens militaires d''active, qui sont redevables legalement de 5 annees au titre de la disponibilite, entrent pendant cette periode dans la composition de ...'),
    (936, 4, 0, 'Quelle est la philosophie du commandement par intention'),
    (939, 4, 0, 'Lequel de ces États ne fait pas partie de l''OTAN ?'),
    (940, 4, 0, 'Laquelle de ces formations n''est pas subordonnée au Commandement des action s spéciales Terre (CAS T), qui succède au COM FST dans le cadre du modèle "armée de Terre de combat"'),
    (941, 4, 0, 'Laquelle de ces formations n''appartient pas à la 11e Brigade parachutiste ?'),
    (942, 4, 0, 'Quelle formation n''est pas placée sous l''autorité du général commandant la 27e BIM ?'),
    (944, 4, 0, 'Quel est l''unique régiment d’appui nucléaire, radiologique, biologique et chimique (NRBC) de l''armée de Terre'),
    (946, 4, 0, 'Laquelle de ces formations entre dans la composition des Forces armées de la zone sud de l’océan Indien (FAZSOI) ?'),
    (947, 4, 0, 'En 2023, parmi les formations suivantes, laquelle n''est pas subordonnée au Commandement du renseignement (COMRENS) ?'),
    (948, 4, 1, 'Le TTA 107 est …'),
    (949, 4, 0, 'Le Commandement des forces spéciales Terre (CFST) est devenu le 1er janvier 2024 :'),
    (952, 4, 0, 'Article 7 : "Prêt à l''engagement, je m''entraîne sans relâche et recherche l''excellence". Quel comportement ne se rapporte pas à cet article ?'),
    (953, 4, 0, 'Quel est le nom de l’unité des sapeurs-pompiers de Paris qui est spécialisée dans les interventions en milieux naturels et artificiels difficiles d’accès ?'),
    (955, 4, 0, 'Une seule de ces affirmations concernant la 27e Brigade d''infanterie de montagne (27e BIM) est juste. Laquelle ?'),
    (956, 4, 0, 'Qu''est-ce que le HCECM ?'),
    (957, 4, 0, 'Quel texte constitue le fondement réglementaire de l’exercice du métier militaire ?'),
    (959, 4, 1, 'Laquelle de ces appellations désigne un système de mise en œuvre au sein d''une patrouille légère de recherche par imagerie (PLRI) ?'),
    (960, 4, 1, 'Laquelle de ces appellations désigne un système de radar d’observation des intervalles en service dans l''armée de Terre ?'),
    (961, 4, 1, 'Quel fusil remplace le FRF2 ?'),
    (962, 4, 1, 'Lequel n''est pas un véhicules moyens et legers'),
    (964, 4, 0, 'Laquelle de ces formations de l''infanterie fait partie de la Brigade franco-allemande ?'),
    (966, 4, 1, 'Le TTA 107 est,,,'),
    (967, 4, 0, 'Laquelle de ces affirmations concernant le Régiment de marche du Tchad (RMT) est fausse'),
    (968, 4, 0, 'L''un de ces organismes n''est pas subordonné au CEMA. Lequel ?'),
    (969, 4, 0, 'Lequel de ces organismes n''est pas placé sous l''autorité du CEMA ?'),
    (970, 4, 0, 'Parmi ces affirmations relatives au SMA, laquelle est inexacte ?'),
    (971, 4, 0, 'L''une des affirmations sur le Service militaire adapté (SMA) est fausse. Laquelle ?'),
    (972, 4, 1, 'Quel est le nom du nouveau véhicule léger qui remplace progressivement le véhicule P4 ?'),
    (973, 4, 1, 'L''engin blindé de reconnaissance et de combat (EBRC) Jaguar est destiné à remplacer :'),
    (977, 4, 0, 'Dans le cadre du modèle "armée de Terre de combat", lequel de ces organismes de formation n''est pas rattaché au nouveau Pôle formation de la DRHAT'),
    (979, 4, 1, 'Dans le cadre du programme Scorpion, le futur Véhicule bli ndé d''aide à l''engagement (VBAE) est destiné à remplacer ...'),
    (980, 4, 0, 'Quels accords ont été ralentis en raison des tensions au Levant'),
    (982, 4, 0, 'Le 1er régiment d''artillerie est spécialisé dans ?'),
    (983, 4, 3, 'Quels acteurs ont intensifié leurs actions déstabilisatrices en mer Rouge'),
    (984, 4, 0, 'Pour rappel quels sont les 6 principes de commandement de l''armée de Terre ?'),
    (987, 4, 1, 'Pour l''armée de Terre, Scorpion" est'),
    (988, 4, 0, 'Quels sont les fondements majeurs indispensables à l''exercice de commandement ?'),
    (993, 4, 0, 'L''UIISC designe :'),
    (996, 4, 0, 'Le commandement s''exerce en permanence dans trois dimensions distinctes mais complémentaires. Laquelle n''en fait pas partie ?'),
    (1001, 4, 1, 'Quelle caracteristique du GRIFFON est incorrecte ?'),
    (1003, 4, 0, 'Quelles sont les Valeurs qui composent le socle de l''armée de terre, l''identité du soldat ?'),
    (1008, 4, 0, 'Le CCF fait partie des grands commandeurs de quel autorité est-il placé ?'),
    (1011, 4, 1, 'Que signifie l''acronyme MEPAC ?'),
    (1012, 4, 0, 'Quelles sont les quatre principes pour garantir la survivabilité des poste de commandement (PC) en haute intensité ?'),
    (1014, 4, 0, 'L''armée de terre de combat s''articule en trois axes quelles sont-elles ?'),
    (1021, 4, 1, 'Que signifie l''acronyme MEPAC'),
    (1025, 4, 0, 'Comment se nomme le nouveau stage proposé par le 9e régiment d''infanterie de marine en Guyane ?'),
    (1032, 4, 0, 'Quels sont les trois domaines de leviers de subsidiarité confiés par la DRHAT aux brigadiers ?'),
    (1033, 4, 0, 'Quel est la signification du terme "OIV" ?'),
    (1034, 4, 3, 'En Janvier 2025 la brigade logistique (B.LOG) a réalisé un exercice d''une dizaine de jours en Champagne quel est le nom de cet exercice ?'),
    (1035, 4, 0, 'Est-ce que l''expérimentation de l''innovation est l''apanage du CCF'),
    (1036, 4, 0, 'Parmi ces propositions, laquelle ne fait pas partie des vertus cardinales de l''armée de terre telles qu''elles sont définies dans le Livre Vert ?'),
    (1037, 4, 1, 'Quel est le nom du casque du futur en phase d''exploration et utilisé par certaines forces spéciales étrangères?'),
    (1041, 4, 0, 'Qui a ecrit " La discipline est l''âme de tout le genre militaire ; si elle n''est pas etablie avec sagesse et executee avec une fermete inebranlable, l''on ne saurait avoir de troupes. " ?'),
    (1045, 4, 0, 'Sur le visuel de la vision stratégique du CEMAT, on peut voir un anneau sur lequel sont inscrits les termes qui caractérisent la nouvelle armée de Terre de combat : "puissance","réactivité", "forces morales" et :'),
    (1046, 4, 1, 'Le mortier de 120 mm 2R2M du MEPAC est produit par ?'),
    (1049, 4, 0, 'Complétez la phrase : "Le commandement s''exerce en permanence dans ... dimensions.".'),
    (1050, 4, 0, 'Commandé par la DRHAT, de combien d''échelons locaux de gestion administrative (ELGA) seront déployés à Metz, Lyon, Marseille et Bordeaux ?'),
    (1051, 4, 0, 'Dans l''organigramme "Armée de Terre de combat 2024", à quel pôle de la DRHAT les groupements de recrutement et de sélection sont-ils rattachés ?'),
    (1052, 4, 0, 'Quel est l''objectif de l''accompagnement individualisé de la carrière des subordonnés ?'),
    (1053, 4, 0, 'Au 1er juillet 2025, les UIISC n°1- 4 et 7 prendront l''appellation de ?'),
    (1055, 4, 1, 'Le 14e RILP (régiment d''infanterie et de logistique parachutiste)est le seul régiment à mettre en oeuvre des unités mobiles de …?'),
    (1058, 4, 3, 'Dans quels pays la MINURCAT a-t-elle été déployée ?'),
    (1060, 4, 1, 'Quel SI pour standardiser les supports de suivi et faciliter les remontee d''information ?'),
    (1063, 4, 1, 'Une de ces affirmations concernant l''Engin blindé de reconnaissance et de combat (EBRC) Jaguar est fausse. Laquelle ?'),
    (1065, 4, 1, 'Laquelle de ces affirmations concernant le nouveau fusil de précision SCAR-H-PR est fausse ?'),
    (1075, 4, 5, 'L''objectif stratégique numéro 4 s''intitule "Une résilience cyber de premier rang". Savez-vous où est basé le Groupement de Cyberdéfense des Armées (GCA) ?'),
    (1078, 4, 0, 'Le commandement de combat futur (CCF) organise en 2025 la 1re édition des journées du combat futur comment s''appelle ce salon ?'),
    (1079, 4, 0, 'Dans la préface du Livre Vert, le général Jean-Pierre Bosser pose cette question qui touche à la morale : "Est-il possible de vaincre ... ?"'),
    (1082, 4, 1, 'Quelle définition d''acronyme du programme SCORPION est erronée ?'),
    (1083, 4, 1, 'Parmis ces drones, trouvez l''intrus ?'),
    (1084, 4, 0, 'Quelle est le nom de l''unité de l''armée de Terre dédiée aux robots aéroterrestres ?'),
    (1086, 4, 0, 'Quelle est la signification de "SIRPA TERRE" dans le livre kaki ?'),
    (1090, 4, 0, 'Pourquoi les subordonnés adhèrent-ils plus fortement à une décision ?'),
    (1096, 4, 0, 'Quels sont les trois efforts de l''armée de terre au combat ?'),
    (1097, 4, 1, 'L''engin d''intervention et de protection BUFFALO est de fabrication :'),
    (1098, 4, 0, 'Selon le Livre Vert, le soldat de l''armée de Terre agit dans un milieu complexe caractérisé par l''enchevêtrement de trois dimensions. Lesquelles ?'),
    (1100, 4, 1, 'Que veut dire EGAME'),
    (1102, 4, 1, 'Que veut dire TIC'),
    (1103, 4, 0, 'Quels sont les composantes stratégiques de la France dans le cadre de la dissuasion nucléaire ?'),
    (1105, 4, 0, 'Sur le visuel de la vision stratégique du CEMAT, on peut voir un anneau sur lequel sont inscrits les termes qui caractérisent la nouvelle armée de Terre de combat : "puissance", "réactivité", "forces morales" et :'),
    (1106, 4, 0, 'Pourquoi le Livre Bleu sur l’exercice du commandement a-t-il été réédité ?'),
    (1107, 4, 0, 'De combien de brigades la 3e Division est-elle composée'),
    (1108, 4, 0, 'Conformément au décret n° 2019-1271 du 2 décembre 2019 relatif aux modalités de classification et de protection du secret de la défense nationale, combien y a-t-il de niveaux de classification ?'),
    (1111, 4, 0, 'Fin 2023, combien de "maisons Athos" comptait le dispositif de réhabilitation psycho sociale dédié à l’accompagnement des militaires blessés psychiques en service ?'),
    (1112, 4, 0, 'La première et troisième divisions sont régionalisées sur un mandat de ?'),
    (1114, 4, 1, 'Qu''est-ce qu''un DRAC ?'),
    (1115, 4, 1, 'Qu''est-ce que le RASIT ?'),
    (1117, 4, 1, 'Qu''est ce que le P3TS'),
    (1118, 4, 0, 'Quelle est l''appréciation erronée à corriger selon le livre bleu ?'),
    (1119, 4, 1, 'Qu''est ce que le Kit Lotak'),
    (1122, 4, 1, 'MORPHEE concerne :'),
    (1123, 4, 1, 'Qu''est-ce que l''ERYX ?'),
    (1124, 4, 1, 'Le véhicule blindé-multi-rôle-léger Serval (VBMR-L) est amené à remplacer ?'),
    (1129, 4, 1, 'Dans le cadre du programme Scorpion, le VBMR Griffon a vocation à remplacer'),
    (1134, 4, 0, 'Que veut dire le sigle VDAT ?'),
    (1135, 4, 0, 'La fonction strategique "protection-resilience" recouvre, entre autres, la securisation des territoires et ZEE. Que signifie ce sigle'),
    (1136, 4, 1, 'Une de ces réponses concernant le supercalculateur ASGARD n''est pas bonne laquelle ?'),
    (1137, 4, 0, 'Quels sont les six principes fondamentaux du commandement décrits dans le Livre Bleu ?'),
    (1138, 4, 0, 'Où le commandement par intention doit-il être pratiqué'),
    (1139, 4, 0, 'Quelle est la « raison d''être » de toute armée selon le document ?'),
    (1140, 4, 0, 'La Revue nationale stratégique 2025 a été publié par ?'),
    (1141, 4, 0, 'La CISPAT est rattachée à ?'),
    (1142, 4, 0, 'Quelles sont les quatre conditions permettant de créer la fraternité ?'),
    (1143, 4, 0, 'Dans le cadre du principe d''exigence, que doit cultiver le chef pour suggérer au subordonné son propre comportement ?'),
    (1144, 4, 0, 'Quelle est la première compétence attendue d''un chef ?'),
    (1145, 4, 0, 'Sur quels types de courage repose l''esprit de décision ?'),
    (1146, 4, 0, 'Quels sont les trois dimensions du décideur militaire identifiées dans « Commander aujourd''hui » ?'),
    (1147, 4, 0, 'Quelles sont les quatre étapes du cycle de l''exercice du commandement ?'),
    (1148, 4, 0, 'Quel principe fondateur est renforcé par le modèle « Au contact » pour insuffler plus de liberté dans les rapports hiérarchiques ?'),
    (1149, 4, 0, 'Quelle vertu est décrite comme la « clé de voûte de toutes les vertus » pour le chef ?'),
    (1150, 4, 0, 'Selon le Maréchal Lyautey, quelle est la « véritable école du commandement » ?'),
    (1152, 4, 0, 'Que signifie l''expression « être obéi d''amitié » selon le général Tanant ?'),
    (1153, 4, 0, 'Quel est le but de la « singuralité militaire » selon le document ?'),
    (1154, 4, 0, 'Que signifie le verbe latin « commendare » à l''origine du mot commander ?'),
    (1155, 4, 0, 'Quel rôle central occupe le sous-officier dans la chaîne de commandement ?'),
    (1156, 4, 0, 'Quelles sont les trois dimensions sur lesquelles repose l''autorité ?'),
    (1158, 4, 0, 'Quelle expression définit la philosophie du commandement par intention (CPI) ?'),
    (1161, 4, 0, 'Que doit faire un subordonné face à un ordre manifestement illégal ?'),
    (1162, 4, 0, 'Comment le soldat doit-il commander selon l''article 5 du Code d''honneur ?'),
    (1163, 4, 0, 'Selon le général Lagarde, pourquoi le commandement est-il considéré comme un « art appliqué » ?'),
    (1164, 4, 1, 'Quel est le rôle principal du Véhicule Blindé Léger (VBL)'),
    (1165, 4, 0, 'Dans le cadre de la participation, quelle est la forme la plus haute de contribution à une œuvre commune ?'),
    (1166, 4, 0, 'Quelles sont les trois dimensions complémentaires du décideur militaire moderne ?'),
    (1167, 4, 0, 'Quel est le processus cyclique en quatre étapes de l''exercice du commandement ?'),
    (1168, 4, 0, 'Quel maréchal affirmait que « le cœur humain est le point de départ de toute chose à la guerre » ?'),
    (1169, 4, 1, 'Qu''est-ce que MILISTORE ?'),
    (1170, 4, 0, 'Quels sont les trois fondements de l''autorité décrits dans le livret du sous-officier ?'),
    (1171, 4, 0, 'Quelle qualité est décrite comme étant « indispensable pour susciter l''adhésion » et « la seule façon de commander » ?'),
    (1172, 4, 1, 'Qu''est ce que le NEROD RF'),
    (1173, 4, 0, 'Trouvez l''intrus, le commandement par intention est :'),
    (1174, 4, 3, 'Qu''est ce que la Blue Line et dans quel pays se trouve t-elle ?'),
    (1175, 4, 0, 'Quelle affirmation sur le service national universel (SNU) est correcte ?'),
    (1176, 4, 0, 'Quelle est la « première entre toutes » les vertus militaires selon le Livre Vert ?'),
    (1178, 4, 0, 'D''après l''article 5 du Code d''honneur, comment un chef doit-il commander ses subordonnés ?'),
    (1179, 4, 0, 'Que doit faire un soldat s''il reçoit un ordre manifestement illégal selon le guide d''éthique ?'),
    (1180, 4, 1, 'Dans le cadre du programme Scorpion, le futur Vehicule blinde d''aide à l''engagement (VBAE) est destine à remplacer …'),
    (1184, 4, 0, 'Le plan ministériel VEM est l''une des nouveautés de l''année 2024. Que signifie VEM ?'),
    (1185, 4, 3, 'Le plan HEPHAISTOS concerne :'),
    (1187, 4, 0, 'Quel est le rôle du Président de la République vis-à-vis des armées selon l''article 5 de la Constitution ?'),
    (1188, 4, 0, 'Le 28e groupe géographique prend l’appellation au 1/06/2026 de'),
    (1189, 4, 0, 'Quels sont les deux types de composantes de la dissuasion nucléaire française ?'),
    (1190, 4, 1, 'Quel nouveau programme est l''aspect le plus emblématique de la transition capacitaire de l''armée de Terre ?'),
    (1191, 4, 0, 'Comment le général de Gaulle définit-il l''exercice du commandement dans « Vers l''armée de métier » ?'),
    (1192, 4, 0, 'Comment est définie l''agilité selon la doctrine Action Terrestre Future ?'),
    (1193, 4, 0, 'Quelle est la définition de la « Force morale » dans le contexte militaire ?'),
    (1194, 4, 1, 'Quel système remplace l''ancien mode de coordination par « systèmes isolés » dans la révolution SCORPION ?'),
    (1195, 4, 5, 'Quelle division française a son quartier général à Marseille et est orientée vers la projection d''urgence ?'),
    (1196, 4, 0, 'Selon le document, que transforme l''affection réciproque entre le chef et le subordonné ?'),
    (1197, 4, 0, 'Quel pourcentage des sous-officiers de l''Armée de Terre sont issus du rang (anciens militaires du rang) ?'),
    (1198, 4, 0, 'Quel organisme interarmées est dédié à l''insertion des jeunes en métropole depuis 2015 ?'),
    (1199, 4, 0, 'Quelle est la cible de dénonciation (attrition) en formation initiale pour le recrutement Direct (D) ?'),
    (1200, 4, 0, 'Quel est l''un des trois « combats » prioritaires du plan d''action de la DRHAT pour les ressources humaines ?'),
    (1201, 4, 1, 'Quel projet vise à créer la première « unité robotique de combat » expérimentale ?'),
    (1202, 4, 0, 'Quelle priorité du CEMAT vise à lutter contre les dérives relationnelles au sein de l''institution ?'),
    (1203, 4, 0, 'Quelles sont les sujétions propres aux militaires mentionnées dans le statut général ?'),
    (1204, 4, 0, 'Quel phénomène démographique affectera les viviers de recrutement d''ici 2035 selon la PRH ?'),
    (1206, 4, 0, 'Selon le colonel Ardant du Picq, quel est l''instrument premier du combat ?'),
    (1207, 4, 0, 'Quel document rappelle les fondements des principes d''autorité et d''obéissance ?'),
    (1208, 4, 0, 'Quels sont les six principes fondamentaux qui forment l''hexagone des vertus du commandement selon le Livre Bleu ?'),
    (1209, 4, 0, 'Selon le principe d''exigence, quelle est la vertu centrale que le chef doit cultiver pour être un modèle ?'),
    (1210, 4, 0, 'Quelle est la première compétence attendue d''un chef militaire selon la doctrine ?'),
    (1211, 4, 0, 'Sur quelles formes de courage repose principalement l''esprit de décision d''un chef ?'),
    (1212, 4, 0, 'Selon le principe de justice, que signifie « être juste » pour un chef ?'),
    (1213, 4, 0, 'Selon le Maréchal de Belle-Isle, que doit chercher un colonel pour réussir son commandement ?'),
    (1214, 4, 0, 'Pour le Colonel Ardant du Picq, quel est le but de la discipline ?'),
    (1215, 4, 0, 'D''après le Général de Gaulle, quelle est la véritable école du commandement ?'),
    (1216, 4, 0, 'Que signifie le principe de « subsidiarité » dans le commandement militaire ?'),
    (1217, 4, 0, 'Quelle est la place centrale occupée par les sous-officiers dans la chaîne de commandement ?'),
    (1218, 4, 0, 'Comment est défini l''esprit de décision pour un chef selon le référentiel de l''ENSOA ?'),
    (1219, 4, 0, 'Dans le cadre de la discipline du commandement par intention, que doit faire le chef concernant son autorité ?'),
    (1220, 4, 0, 'Que signifie la « subsidiarité en actes » dans le texte du général Schill ?'),
    (1221, 4, 0, 'Quel sentiment le commandement par intention appelle-t-il entre le chef et le subordonné ?'),
    (1222, 4, 0, 'Selon le document, qu''est-ce qui constitue le socle de la force morale du soldat face à l''isolement au combat ?'),
    (1223, 4, 0, 'Quelle vertu militaire est décrite comme le « ressort intérieur » incitant à conserver l''estime de soi et des autres ?'),
    (1224, 4, 0, 'Dans quel cas la désobéissance d''un subordonné est-elle considérée comme un devoir ?'),
    (1225, 4, 0, 'Quelle vertu transcende le courage en héroïsme au combat ?'),
    (1226, 4, 0, 'Quelles sont les trois valeurs mentionnées dans l''article 2 du Code d''honneur du soldat ?'),
    (1227, 4, 0, 'Que stipule l''article 8 concernant le comportement au combat vis-à-vis des camarades ?'),
    (1230, 4, 0, 'Quelle catégorie de réservistes est soumise à l''obligation de disponibilité pendant les cinq ans suivant la fin de leur service actif ?'),
    (1231, 4, 0, 'Quel organisme assure la coordination interministérielle et le traitement des sujets transverses aux réserves ?'),
    (1232, 4, 0, 'Comment est défini l''« avertissement nucléaire » dans la doctrine française ?'),
    (1233, 4, 0, 'Quel est l''objectif majeur de la transformation structurelle de l''armée de Terre à l''horizon 2030 ?'),
    (1234, 4, 0, 'Quel est le nouveau délai cible pour déployer une division « haute intensité » d''ici 2027 ?'),
    (1235, 4, 0, 'Quelle est la durée de service effectif requise pour le recrutement sous-officier par la voie semi-directe (SD) ?'),
    (1236, 4, 0, 'Quel philosophe ou stratège a théorisé la « vertu guerrière » citée dans les fondements ?'),
    (1238, 4, 0, 'Quelle citation du Colonel Ardant du Picq souligne l''importance du facteur humain ?'),
    (1239, 1, 0, 'Article 8 : "Au combat, je n''abandonne ni mon arme, ni mes camarades morts ou .........".A combien de principes le droit des conflits armés répond-il ?'),
    (1240, 2, 1, 'D''ici à décembre 2025, Combien de MEPAC sont autorisés à l''emploi dans les forces ?'),
    (1241, 4, 0, 'En matière de fidélisation, quel est le taux visé (par le modèle MDR RH) pour le renouvellement du premier contrat de 5 ans'),
    (1242, 4, 0, 'Dans l''organigramme "Armée de Terre de combat 2024", quelle est l''autorité de tutelle de la Section technique de l''armée de Terre (STAT) ?'),
    (1243, 4, 0, 'Parmi ces propositions, laquelle est désormais la 6e fonction stratégique ?'),
    (1244, 4, 0, 'Le centre d’enseignement technique de l’armée de Terre (CETAT) est sous la responsabilité du …'),
    (1246, 4, 0, 'Il y a  4 ELGA créé de 2025 trouver l''intrus'),
    (1256, 4, 0, 'Quel est la signification du sigle NPRM ?'),
    (1259, 4, 0, 'Quels sont les trois axes d''efforts identifiés dans sa stratégie militaire générale et qui caractérise l''outil de résilience à la "cohésion nationale" ?'),
    (1261, 4, 0, 'Que signifie le sigle PIAT ?'),
    (1263, 4, 1, 'Quel est l''objectif principal du système SCORPION'),
    (1265, 4, 3, 'Depuis plus de 40 ans les armées françaises sont présentes au Liban. Ils sont engagés pour faire appliquer la résolution …….?'),
    (1266, 4, 0, 'Quatre conditions principales permettent de creer cette fraternite. Parmi les suivantes une n''est pas la bonne.'),
    (1267, 4, 1, 'Dans quel régiment les deux premiers véhicules JAGUAR ont-ils été livrés en décembre 2021 ?'),
    (1268, 4, 1, 'Le SDZ est un ?'),
    (1269, 4, 0, 'Lequel des États n''est pas membre de l''OTAN ?'),
    (1270, 4, 1, 'Laquelle des affirmations suivantes concernant le HK 269 est fausse ?'),
    (1274, 4, 0, 'Combien existe-t-il de regiments du service militaire adapte (RSMA) ?'),
    (1275, 4, 1, 'Laquelle de ces affirmations concernant le nouveau système dedrones tactiques (SDT  Patroller) est fausse ?'),
    (1276, 4, 1, 'Designez l''intrus parmi les systemes ou materiels suivants :'),
    (1277, 4, 1, 'Tous sont aussi des drones sauf un lequel ?'),
    (1281, 4, 1, 'Quel est la signification du terme "THA" ?'),
    (1285, 4, 1, 'Lequel de ces véhicules a une vitesse maximale égale à 100 km/h ?'),
    (1286, 4, 1, 'Le Griffon est amené à remplacer ……'),
    (1287, 4, 1, 'Caractéristique du SERVAL'),
    (1288, 4, 1, 'Lequel de ces véhicules est en service aux 503e et 515e Régiments du Train ?'),
    (1289, 4, 1, 'Que veut dire FELIN ?'),
    (1290, 4, 0, 'Selon le Maréchal de Saxe, quel est le point de départ de toute chose à la guerre ?'),
    (1291, 4, 0, 'Qu''est-ce qui constitue un des fondements majeurs de l''exercice du commandement en permettant l''adhésion ?'),
    (1292, 4, 0, 'Quelles sont les deux formes que peut revêtir la participation ?'),
    (1293, 4, 0, 'Quel principe de commandement privilégié par l''armée de Terre est défini par « l''initiative des modalités confiée au subordonné » ?');

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM reviewed_theme_assignments a
        LEFT JOIN public.question_bank q ON q.id = a.id
        WHERE q.id IS NULL OR q.question IS DISTINCT FROM a.expected_question
            OR q.theme_id NOT IN (a.previous_theme, a.target_theme)
            OR q.theme_id IS NULL
    ) THEN
        RAISE EXCEPTION 'Question bank changed since concordance audit; review before applying';
    END IF;
END $$;

UPDATE public.question_bank q
SET theme_id = a.target_theme
FROM reviewed_theme_assignments a
WHERE q.id = a.id AND q.theme_id IS DISTINCT FROM a.target_theme;

COMMIT;
